// <auto-generated />
using System;
using History.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace History.Infrastructure.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    [Migration("20190609072646_IntialCreate")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("History.Infrastructure.Entities.HistoryEntity", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("ProfileId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Genres");

                    b.Property<string>("ReleaseYear");

                    b.Property<double?>("TimeWatched");

                    b.Property<string>("VideoId");

                    b.Property<string>("WatchingItemId");

                    b.Property<int>("WatchingItemType");

                    b.HasKey("UserId", "ProfileId");

                    b.ToTable("HistoryEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
